apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: novagen
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels: { app: mongo }
  template:
    metadata:
      labels: { app: mongo }
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports: [{ containerPort: 27017 }]
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom: { secretKeyRef: { name: novagen-secrets, key: MONGO_INITDB_ROOT_USERNAME } }
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom: { secretKeyRef: { name: novagen-secrets, key: MONGO_INITDB_ROOT_PASSWORD } }
          volumeMounts:
            - name: mongodata
              mountPath: /data/db
          resources:
            requests: { cpu: "250m", memory: "512Mi" }
            limits: { cpu: "1", memory: "1Gi" }
  volumeClaimTemplates:
    - metadata: { name: mongodata }
      spec:
        accessModes: ["ReadWriteOnce"]
        resources: { requests: { storage: 20Gi } }
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: novagen
spec:
  selector: { app: mongo }
  ports: [{ port: 27017, targetPort: 27017 }]
  clusterIP: None
