"""The ONLY module in the entire NovaGen codebase that references SNS Agent
Workbench. Every other service, including the gateway and frontend, has zero
knowledge of this system.

REAL API, CONFIRMED BY HAND (not guessed): SNS Agent Workbench
(agents.snsihub.ai) is a visual node-based workflow builder aimed at
students, with no general REST API. It integrates via a "Webhook Trigger"
node placed inside a specific workflow: that node listens on
POST https://agents.snsihub.ai/webhook/<auto-generated-uuid-path>, and
whatever JSON body you POST becomes the workflow's input data. The workflow
must be built with a connected downstream node and Deployed in the SNS
Workbench UI before that URL is live.

There's exactly one webhook URL for the whole integration, not one per
event type — the deployed SNS Workbench workflow is responsible for
branching on the `event` field if it needs different behavior per event.
Every function below is a thin wrapper around the same POST, differing only
in what `event` and payload they send. Set SNS_WORKBENCH_WEBHOOK_URL in
.env once you've built and deployed the workflow; every function here
no-ops safely (returns dispatched: False) if it isn't configured, so local
dev without an SNS Workbench account never gets blocked on this.
"""
import httpx

import sys
sys.path.append("/app")
from shared.config import get_settings  # noqa: E402

settings = get_settings()


def _webhook_configured() -> bool:
    return bool(settings.sns_workbench_webhook_url)


def _post_event(event: str, data: dict) -> dict:
    if not _webhook_configured():
        return {"dispatched": False, "reason": "sns_webhook_not_configured", "text": None}

    with httpx.Client(timeout=30.0) as client:
        resp = client.post(settings.sns_workbench_webhook_url, json={"event": event, **data})
        resp.raise_for_status()
        try:
            body = resp.json()
        except ValueError:
            body = {}

    return {"dispatched": True, "text": _extract_generated_text(body)}


def _extract_generated_text(body: dict) -> str | None:
    """SNS Agent Workbench wraps its response in a platform-specific envelope
    (`{"items": [{"json": {...}}], ...}`). The actual LLM-generated text lives
    somewhere inside that inner `json` object, under whichever field name the
    deployed workflow's LLM Node happens to output - this varies by how the
    workflow was built, so we check the common possibilities rather than
    assuming one. Returns None (never a fabricated string) if nothing usable
    is found, so callers can fall back to their own default message instead
    of silently displaying an empty automation response as if it were real
    content."""
    try:
        items = body.get("items") or []
        if not items:
            return None
        inner = items[0].get("json") or {}
        for key in ("output", "text", "response", "content", "message", "result"):
            value = inner.get(key)
            if isinstance(value, str) and value.strip():
                return value.strip()
        return None
    except (AttributeError, IndexError, TypeError):
        return None


def dispatch_stage_job(pipeline_run_id: str, stage: str) -> dict:
    """Fired on every pipeline stage advance (workflow-service -> automation-service -> here)."""
    return _post_event("pipeline_stage", {"pipeline_run_id": pipeline_run_id, "stage": stage})


def check_and_queue_retraining() -> dict:
    """Fired daily by Celery Beat (see worker.py's beat_schedule)."""
    return _post_event("retrain_check", {})


def notify_report_generated(report_id: str, title: str, report_format: str, download_url: str) -> dict:
    """Fired after report-service successfully generates a report, so the SNS
    workflow can (for example) draft a notification summarizing what's in it."""
    return _post_event(
        "report_generated",
        {"report_id": report_id, "title": title, "format": report_format, "download_url": download_url},
    )


def answer_chat_query(query: str, context: dict) -> dict:
    """Real-time chat: unlike the other functions here, this needs an
    immediate reply for a waiting user, so it calls SNS Workbench directly
    rather than going through Celery. `context` carries real facts about the
    asking user (their data counts, current service health) so SNS Workbench
    can ground its answer in reality instead of generic platform knowledge
    alone. Requires a 5th Switch route (event == "chat_query") connected to
    an LLM Node in the deployed workflow - if that route doesn't exist yet,
    the event falls through to the workflow's Fallback output and this
    returns text=None, same as any other unmatched event; callers should
    have their own fallback answer ready."""
    return _post_event("chat_query", {"query": query, "context": context})


def notify_dispatch(user_id: str, title: str, body: str | None) -> dict:
    """Fired whenever a notification is being sent to a user, so the SNS
    workflow can enrich/rewrite the message (e.g. via its AI Transform node)
    before or alongside the real notification record being created in
    notification-service. This does not replace notification-service — see
    worker.py's dispatch_notification task, which calls both."""
    return _post_event("notification", {"user_id": user_id, "title": title, "body": body or ""})
